version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: dev
  ignore:
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: mermaid
    versions:
    - 8.9.0
    - 8.9.1
    - 8.9.2
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: babel-eslint
    versions:
    - 10.1.0
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
  - dependency-name: clipboard
    versions:
    - 2.0.6
    - 2.0.7
  - dependency-name: markdown-it-anchor
    versions:
    - 7.0.0
    - 7.0.1
    - 7.0.2
  - dependency-name: lodash
    versions:
    - 4.17.20
